### ISSUE TITLE
Parameter Exploration Example

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/docs#18]
It may be worthwhile documenting the preferred approach to parameter exploration for FLAME GPU models. 

I.e. as of 1.5 this is:

1. Use Environment constants for parameters
2. Load these values from the XML Model file (or a custom init function)
3. Initialise population via Init function
4. Use 1 folder per init file to avoid overwriting 
5. Jobs can then be ran sequentially on a single device (or multiple concurrent runs for very small models) or batched across multiple devices (i.e high throughput on clusters)

**Comment by Robadob** [comment]
Could you not allow env constants to be set via runtime args, and similarly
output file path?

Much cleaner from a batch run point of view imo.

`-env radius:5` or something would be trivial to parse.

**Comment by ptheywood** [comment]
Output file path as of 1.5 can effectively be set, by providing a path to a directory rather than any 0.xml file, in which case command line args could be an option, and as you suggest probably be cleaner for batch running. 

We would need to decide on order of precedence if this were to be implemented, I would guess that command line would override XML file which overrides defaultValue. 

As for argument syntax I agree we probably need to prefix with `--environment` or `-e` and follow with a keyvalue pair, though I would probably choose `radius=5` rather than `:` . We could then support comma separated lists per `-e` so the following would be valid options:

+ `--environment radius=10 --environment seed=12`
+ `-e radius=10 -e seed=12`
+ `-e radius=10,seed=12` 

Which as you suggest should not be too difficult to parse. I don't think we need to worry about constant names containing `=` or `,` either as then the file would not even compile (although the message won't be particurlaly clear to the user, perhaps the name should be XML validated via regex to only contain `[a-zA-Z0-9_]` although in addition it should not start with a number either...
