### ISSUE TITLE
Various Updates for 1.5

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/docs#4]
+ [x] Instrumentation constants
+ [x] Limitations of statically allocated memory (2GB limit on windows) which effects agent populations, message list size and the number of bins available for spatially partitioned messaging.
+ [x] The current Linux build process
+ [x] Step Functions 
+ [x] Analytics functions such as reductions
    + [x] Including that these are not available for agent variable arrays
+ [x] Upcoming host-based agent creation (init and step functions)
+ [x] `PAUSE_ON_START` in `visualisation.h`

We may wish to:
+ [x] Remove the technical report from the repository? **OR** Replace the technical report with a pdf of the new documentatiojn
+ [x] Update the README to point to the documentation.

From FLAMEGPU/FLAMEGPU#66

**Comment by ptheywood** [comment]
Host agent creation covered by 496257e

`PAUSE_ON_START` covered by 2a775d4

Technical report removed by a feature branch on the main Repo, and the rc1.5/readme branch of the main repo now points at this documentation repo and http://docs.flamegpu.com

**Comment by mondus** [comment]
Analytics functions in separate issue #13
