### ISSUE TITLE
Vector and Unsigned Types 

### ISSUE THREAD

**Issue by ptheywood** [FLAMEGPU/docs#7]
We need to add details about the use of vector and unsigned types for 1.5.X

+ [x] Agent Variables
+ [x] Environmental Variables
+ [x] Message Variables
    + Importantly this **does not** support vector types, but might support unsigned? @mondus

**Comment by mondus** [comment]
Add a section (2.8) called FLAME GPU variable types. Needs a table to show where they are supported.

**Comment by ptheywood** [comment]
This still needs some work. Some types are missing and descriptions are possibly unnecessarily long. It may be simpler to refer to the usual/typcial number of bytes used by each type (as x64 systems are the only supported)
